In [37]:
#Data_Masking

In [102]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [103]:
def clean_df(df,cols):
    for col_name in cols:
        keys = {cats: i for i,cats in enumerate(df[col_name].unique())}
        df[col_name] = df[col_name].apply(lambda x: keys[x])
        return df

In [104]:
df = pd.read_csv('HospInfo.csv')

In [105]:
cols =['Hospital_Name','Emergency']

In [106]:
df = clean_df(df,cols)

In [109]:
df = np.array(df)

In [110]:
encoder = LabelEncoder()
a = encoder.fit_transform(df[0:,10])

In [111]:
df[:,10] = a

In [112]:
a

array([1, 1, 1, ..., 0, 1, 1])

In [84]:
#Data_Generilisation

In [85]:
df = np.array(df)

In [86]:
a = df[:,2]

In [87]:
b = a[0]

In [97]:
b

['2505', 'U S HIGHWAY 431 NORTH']

In [ ]:
b = b.split[" ",1]

In [99]:
b

['2505', 'U S HIGHWAY 431 NORTH']

In [93]:
for i in range(40):
    df[:,2][i] = df[:,2][i].split(" ",1)
    df[:,2][i] = df[:,2][i][1]

In [94]:
df[:,2][0]

'U S HIGHWAY 431 NORTH'

In [60]:
#Perubation
df = pd.read_csv('HospInfo.csv')

In [61]:
df['Zip'] = df['ZIPCode'] * 212

In [23]:
df.drop(columns = 'ZIPCode')

,Provider_ID,Hospital_Name,Address,City,State,County Name,Phone Number,Hospital_Type,Hospital_Ownership,Emergency,...,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location,Zip
0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,True,...,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL\n",7622884
1,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,DE KALB,2568453150,Acute Care Hospitals,Proprietary,True,...,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,"200 MED CENTER DRIVE\nFORT PAYNE, AL\n",7625216
2,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,True,...,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL\n",7690936
3,10095,HALE COUNTY HOSPITAL,508 GREEN STREET,GREENSBORO,AL,HALE,3346243024,Acute Care Hospitals,Government - Local,True,...,Not Available,Results are not available for this reporting p...,Below the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"508 GREEN STREET\nGREENSBORO, AL\n",7789728
4,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,MADISON,2568823100,Acute Care Hospitals,Proprietary,True,...,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL\n",7589812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1893,151302,INDIANA UNIVERSITY HEALTH BLACKFORD HOSPITAL,410 PILGRIM BLVD,HARTFORD CITY,IN,BLACKFORD,7653480300,Critical Access Hospitals,Voluntary non-profit - Private,True,...,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"410 PILGRIM BLVD\nHARTFORD CITY, IN\n(40.46890...",10037776
1894,160117,FINLEY HOSPITAL,350 NORTH GRANDVIEW AVENUE,DUBUQUE,IA,DUBUQUE,5635821881,Acute Care Hospitals,Voluntary non-profit - Private,True,...,Above the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,"350 NORTH GRANDVIEW AVENUE\nDUBUQUE, IA\n(42.4...",11024212
1895,170201,"BLUE VALLEY HOSPITAL, INC",12850 METCALF AVENUE,OVERLAND PARK,KS,JOHNSON,9132202866,Acute Care Hospitals,Proprietary,False,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,"12850 METCALF AVENUE\nOVERLAND PARK, KS\n(38.8...",14037156
1896,140167,IROQUOIS MEMORIAL HOSPITAL,200 FAIRMAN STREET,WATSEKA,IL,IROQUOIS,8154325201,Acute Care Hospitals,Voluntary non-profit - Private,True,...,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN,"200 FAIRMAN STREET\nWATSEKA, IL\n(40.765541, -...",12925640
1897,121306,SAMUEL MAHELONA MEMORIAL HOSPITAL,4800 KAWAIHAU ROAD,KAPAA,HI,KAUAI,8088224961,Critical Access Hospitals,Government - State,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20510152

In [ ]:
#Synthetic Data

In [37]:
from faker import Faker

fake = Faker()

In [38]:
def faker_timeseries_rows(num=1, seed=None):
    """
    """
    fake.seed_instance(seed)

    time_gen = fake.time_series(start_date=f"-{num}d", end_date="now", precision=3600)

    output = [
        {
            
            "country": fake.country(),
        }
        for x in range(num)
    ]
    return output

In [39]:
df = pd.DataFrame(faker_timeseries_rows(10, seed=0))
df.head(5)

                 country
0              Sri Lanka
1  Saint Kitts and Nevis
2                   Iraq
3                  Egypt
4          Liechtenstein

In [40]:
import csv
with open('fake_data.csv','w',newline='') as csvfile:
    csv_fake_data = csv.writer(csvfile)
    for i in faker_timeseries_rows(10):
        csv_fake_data.writerow([i])